name: nightly build

on:
  push:
    tags:
      - 'v*'
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: get version
        run: |
          $version = "${{ github.ref }}" -replace "refs/tags/v", ""
          echo "CURRENT_VER=v$version" >>  $env:GITHUB_ENV 
          echo "CURRENT_VER_NUM=$version" >>  $env:GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: czqu/rfu_desktop
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter build windows --release
      - name: archive
        run: |
          $sourcePath = Join-Path -Path (Get-Location) -ChildPath 'build/windows/x64/runner/Release'
          $zipFileName = 'rfu_desktop_windows_x64.zip'
          $destinationPath = Join-Path -Path (Get-Location) -ChildPath $zipFileName
          Compress-Archive -Path $sourcePath\* -DestinationPath $destinationPath -Force
        shell: pwsh

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: "rfu_desktop_*.zip"
          prerelease: false
          tag_name:  ${{ env.CURRENT_VER }}
          token: ${{ secrets.GH_TOKEN }}
          body_path: release_note.md